defaults:
  - controller: gcs_open_loop
  - environment: box_no_rotations
  - problem_generator: problem_generator

problem_generator:
  n_samples: 20

chunk_length: -1
log_every_k_sim_timesteps: 1000
save_meshcats: True
only_generate_initial_positions: False
